### ISSUE TITLE
socket.url.buildpath() path protection unit test fails

### ISSUE THREAD

**Issue by drauschenbach** [nubix-io/gluasocket#1]
I've not been able to isolate it yet, but there seems to be a discrepancy in the uppercase/lowercase hex encoding between Lua and GopherLua.

```bash
$ go test
Running test urltest.lua
testing URL parsing
testing URL building
testing absolute resolution
testing path parsing and composition
testing path protection
%2Feu%3E/%3Cdiego%3F	%2feu%3e/%3cdiego%3f
--- FAIL: TestUrl (0.01s)
        Error Trace:    gluasocket_test.go:75
	            	gluasocket_test.go:51
	Error:      	Received unexpected error:
	            	urltest.lua:18: path composition failed.
	            	stack traceback:
	            		[G]: in function 'error'
	            		urltest.lua:18: in function 'check_protect'
	            		urltest.lua:604: in main chunk
	            		[G]: ?
FAIL
exit status 1
```

**Comment by teejaded** [comment]
Here's the reason:

https://golang.org/pkg/fmt/

```
%x	base 16, lower-case, two characters per byte
%X	base 16, upper-case, two characters per byte
```

```lua
local function protect_segment(s)
    return string.gsub(s, "([^A-Za-z0-9_])", function (c)
        if segment_set[c] then return c
        else return string.format("%%%02X", string.byte(c)) end
    end)
end
```

The options are:
* Change gopher-lua to sub `%X` for `%x`.
* Change luasocket url.lua to use `%x`

**Comment by teejaded** [comment]
Yeah, this test was broken from March 16, 2017 - November 22, 2017.

https://github.com/diegonehab/luasocket/commit/860da0f4b4d9d6ca647ff0a3b15389b41557dec4#diff-4d7e24364dca5902525b2638230cb132

https://github.com/diegonehab/luasocket/commit/2d6a0f7bda9241f827a3edbfa738603c024a423b#diff-12879d8cff28d6b5f233e5658551f8b4

**Comment by drauschenbach** [comment]
@teejaded Would you mind reviewing https://github.com/nubix-io/gluasocket/pull/16, since you did all the investigative work behind it?
